FROM node:latest

# Set working directory name
WORKDIR /backendapp

# Copy the package.json and package-lock.json files to the working directory
COPY package*.json ./

RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Enviromental variable
ENV NODE_ENV development
ENV PORT_ENV 8080

EXPOSE 8080

CMD [ "npm", "run", "dev" ]
